from abc import ABC,abstractmethod
class AnimationProvider(ABC):
 identity:str; capabilities:object
 @abstractmethod
 def available(self): ...
 @abstractmethod
 def validate_request(self,request): ...
 @abstractmethod
 def estimate_cost(self,request): ...
 @abstractmethod
 def estimate_time(self,request): ...
 @abstractmethod
 def submit(self,request): ...
 @abstractmethod
 def status(self,job_id): ...
 @abstractmethod
 def result(self,job_id): ...
 @abstractmethod
 def cancel(self,job_id): ...
