from abc import ABC, abstractmethod
class AnalyticsProvider(ABC):
    identity:str; source:str
    @abstractmethod
    def available(self)->bool: ...
    @abstractmethod
    def validate_request(self, request)->list[str]: ...
    @abstractmethod
    def collect(self, request): ...
    @abstractmethod
    def status(self, request): ...
    @abstractmethod
    def result(self, request): ...
    @abstractmethod
    def cancel(self, request): ...
