from abc import ABC,abstractmethod
class RenderProvider(ABC):
 @abstractmethod
 def available(self):...
 @abstractmethod
 def validate_request(self,r):...
 @abstractmethod
 def submit(self,r):...
 @abstractmethod
 def cancel(self,j):...
