from abc import ABC,abstractmethod
class PublishingProvider(ABC):
 @abstractmethod
 def available(self):...
 @abstractmethod
 def validate_request(self,r):...
 @abstractmethod
 def submit(self,r):...
